### ISSUE TITLE
Minor correction

### ISSUE THREAD

**Issue by l-kotzur** [mujahidfa/inertia-django-vite-vue-minimal#1]
Hey @mujahidfa 

Thanks for the great example. It helped me a lot.

It is working but you need to set DEBUG=True beforehand in the settings.py in order to get it running locally.

Cheers,
Leander

**Comment by mujahidfa** [comment]
Whoops, my bad! It definitely was meant to be True. Was testing prod mode and I must’ve forgotten to switch it back.

Happy to know it helps!
